#!/usr/bin/env bash

url=''
cookies=''
video=false
output=''
is_file=false

check_for_file()
{
  if echo "$url" | grep -q '.txt' && ! echo "$url" | grep -q "https://" ; then
    is_file=true
  fi
}

function video_with_cookies() 
{
   yt-dlp -f bestvideo --cookies "$cookies" -o "%(artist)s - %(title)s.%(ext)s" -P "$output" "$1"
}

function video() 
{
   yt-dlp -f bestvideo -o "%(artist)s - %(title)s.%(ext)s" -P "$output" "$1"
}

function music_with_cookies() 
{
   yt-dlp -f bestaudio -x --audio-quality 0 --audio-format flac -o "%(artist)s - %(title)s.%(ext)s" --cookies "$cookies" -P "$output" "$1"
}

function music() 
{
   yt-dlp -f bestaudio -x --audio-quality 0 --audio-format flac -o "%(artist)s - %(title)s.%(ext)s" -P "$output" "$1"
}

while getopts ":u:c:vo:h" arg
do
   case "$arg" in
     "u")
        url=$OPTARG
        ;;
     "c")
        cookies=$OPTARG
        ;;
     "v")
        video=true
        ;;
     "o")
        output=$OPTARG
        ;;
     "h")
        cat << EOL
Options:
         -u: URL (Can also accept .txt files containing URLs)
         -c: Path to cookies.txt file (Optional)
         -v: Type of download (Default: false for music)[Optional]
         -o: Output file location
         -h: Display help
EOL
        exit
        ;;
     ":")
        echo "ERROR: No argument value for option $OPTARG"
        exit
        ;;
     "?")
        echo "ERROR: Unknown option $OPTARG"
        exit
        ;;
     "*")
        echo "ERROR: Unknown error while processing options"
        exit
        ;;
   esac
done

main()
{
  check_for_file

  if [[ "$is_file" == true ]]; then
    while IFS='' read -r LineFromFile || [[ -n "${LineFromFile}" ]]; do
      tmp_url="$LineFromFile"
      if [ $video == false ]; then
        if [[ $cookies == "" ]]; then
          music "$tmp_url"
        else
          music_with_cookies "$tmp_url"
        fi
      else
        if [[ $cookies == "" ]]; then
          video "$tmp_url"
        else
          video_with_cookies "$tmp_url"
        fi
      fi
    done < "$url"
  else
    if [ $video == false ]; then
      if [[ $cookies == "" ]]; then
        music "$url"
      else
        music_with_cookies "$url"
      fi
    else
      if [[ $cookies == "" ]]; then
        video "$url"
      else
        video_with_cookies "$url"
      fi
    fi
  fi
}

main


