#!/usr/bin/env bash

url=''
cookies=''
video=false
output=''

video_with_cookies() {
   yt-dlp -f bestvideo --cookies $cookies -P $output $url
}

video() {
   yt-dlp -f bestvideo -P $output $url
}

music_with_cookies() {
   yt-dlp -f bestaudio -x --audio-quality 0 --audio-format flac -o "%(artist)s - %(title)s.%(ext)s" --cookies $cookies -P $output $url
}

music() {
   yt-dlp -f bestaudio -x --audio-quality 0 --audio-format flac -o "%(artist)s - %(title)s.%(ext)s" -P $output $url
}

while getopts ":u:c:vo:h" arg
do
   case "$arg" in
     "u")
        url=$OPTARG
        ;;
     "c")
        cookies=$OPTARG
        ;;
     "v")
        video=true
        ;;
     "o")
        output=$OPTARG
        ;;
     "h")
        cat << EOL
Options:
         -u: URL
         -c: Path to cookies.txt file (Optional)
         -v: Type of download (Default: false for music)[Optional]
         -o: Output file location
         -h: Display help
EOL
        exit
        ;;
     ":")
        echo "ERROR: No argument value for option $OPTARG"
        exit
        ;;
     "?")
        echo "ERROR: Unknown option $OPTARG"
        exit
        ;;
     "*")
        echo "ERROR: Unknown error while processing options"
        exit
        ;;
   esac
done

main()
{
  if [ $video == false ]; then
    if [[ $cookies == "" ]]; then
      music
    else
      music_with_cookies
    fi
  else
    if [[ $cookies == "" ]]; then
      video
    else
      video_with_cookies
    fi
  fi
}

main


